Licenta_server/Licenta/urls.py
from django.contrib import admin 
from django.urls import path
#import debug_toolbar
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
#from rest_framework import routers
from interface import views
#router = routers.SimpleRouter() router.register(r'api/rfs/tests', 
#views.TestsViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^', include(router.urls)),
 #   url(r'^__debug__/', include(debug_toolbar.urls)),
    path('interface/', include('django.contrib.auth.urls')),
    path('interface/',include('interface.urls')),
    path('render_info_page/', include('interface.urls', namespace='render_info_page')),
    path('render_control_page/', include('interface.urls', namespace='render_control_page')),
    path('',TemplateView.as_view(template_name='home.html'), name='home'),
    #path('services/', include('services.urls')) 
    #path('adv_search/', include('rfs_tests.urls', 
    #namespace='adv_search')), path('NA/', include('rfs_tests.urls', 
    #namespace='NA'))
]

Licenta_server/interface/urls.py
from django.urls import path, include 
from . import views 
app_name ='interface'

urlpatterns = [
    path('render_info_page', views.render_info_page, name='render_info_page'),
    path('render_control_page', views.render_control_page, name='render_control_page'),
    path('power_on_led', views.power_on_led, name='power_on_led'),
    path('power_off_led', views.power_off_led, name='power_off_led'),
    path('send_info_mail', views.send_info_mail, name='send_info_mail'),
    path('add_new_key', views.add_new_key, name='add_new_key'),
    path('delete_key', views.delete_key, name='delete_key'),
    path('display_current_keys', views.display_current_keys, name='display_current_keys'),
    path('enable_secure_mode', views.enable_secure_mode, name='enable_secure_mode'),
    path('disable_secure_mode', views.disable_secure_mode, name='disable_secure_mode'),
    path('add_new_phone_number', views.add_new_phone_number, name='add_new_phone_number'),
 #path('adv_search', views.adv_search, name='adv_search'), path('NA', 
    #views.not_available_link, name='NA')
#    path('interface/',include('django.contrib.auth.urls'))
]

Licenta_server/templates/home.html
{% extends 'base.html' %}
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=100%, initial-scale=1">
    <meta name="description" content="Controlul Locuintei">
    <link href="/static/css/style.css" rel="stylesheet">
    <title>Controlul Locuintei{% block title %}{% endblock %}</title> 
    
    <header>
        <div class="container">
                <ul class="ul">
                        {% if user.is_authenticated %}
                            <li class="li"><a href="{% url 'home' %}"><font face="Euphemia">DESPRE</font></a></li>
                            <li class="li"><a href="{% url 'interface:render_info_page' %}">INFO</a></li>
                            <li class="li"><a href="{% url 'interface:render_control_page' %}"><font face="Euphemia">CONTROL</font></a></li>
                            {% else %}
                            <li class="li" ><a href="{% url 'home' %}"><fonta face="Euphemia">DESPRE</font></a></li>
 		            <li class="li"><span class="isDisabled"><a href="{% url 'home' %}"><font face="Euphemia">INFO</font></a></span></li>
		            <li class="li" id="index"><a href="{% url 'home' %}"><font face="Euphemia">CONTROL</font></a></li>
                        {% endif %} 
		</ul>
        </div>
    </header>
    {% endblock %}
 	{% block content %}
    <div class="h2">
        {% if user.is_authenticated %}
          <h2> Bun venit {{ user.username  }}!</h2>
          <p>Aceasta aplicatie este dezvoltata in cadrul lucrarii de licenta si serveste ca interfata pentru controlul locuintei.</p>
          <p><a href="{% url 'logout' %}">Deconectare</a></p>   
        {% else %}
          <h2><font face="Euphemnia">Informatii indisponibile</font></h2>
          <p>Nu sunteti autentificat</p>
          <a href="{% url 'login' %}">Autentificare</a>
        {% endif %} 
    </div>
    <div class="container containerMainButtons">
        	
    </div>     
	{% endblock %}